const products = [
  {
    id: 1,
    name: "Fresh Lettuce",
    price: 50,
    unit: "kg",
    farmer: "Juan Dela Cruz",
    location: "Malaybalay City",
    rating: 4.9,
    category: "Vegetables",
    image: "https://images.unsplash.com/photo-1622205313162-be1d5712a43c?auto=format&fit=crop&w=500&q=80",
  },
  {
    id: 2,
    name: "Sweet Corn",
    price: 35,
    unit: "kg",
    farmer: "Maria Santos",
    location: "Valencia City",
    rating: 4.8,
    category: "Vegetables",
    image: "https://images.unsplash.com/photo-1551754655-cd27e38d2076?auto=format&fit=crop&w=500&q=80",
  },
  {
    id: 3,
    name: "Fresh Tomatoes",
    price: 60,
    unit: "kg",
    farmer: "Pedro Garcia",
    location: "Malaybalay City",
    rating: 4.9,
    category: "Vegetables",
    image: "https://images.unsplash.com/photo-1546094096-0df4bcaaa337?auto=format&fit=crop&w=500&q=80",
  },
  {
    id: 4,
    name: "Fresh Carrots",
    price: 45,
    unit: "kg",
    farmer: "Green Valley Farm",
    location: "Bukidnon",
    rating: 4.7,
    category: "Vegetables",
    image: "https://images.unsplash.com/photo-1447175008436-1701707532a2?auto=format&fit=crop&w=500&q=80",
  },
  {
    id: 5,
    name: "Fresh Eggs",
    price: 80,
    unit: "tray",
    farmer: "Happy Hen Farm",
    location: "Malaybalay City",
    rating: 4.8,
    category: "Eggs",
    image: "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?auto=format&fit=crop&w=500&q=80",
  },
  {
    id: 6,
    name: "Native Chicken",
    price: 280,
    unit: "kg",
    farmer: "Bukidnon Poultry",
    location: "Quezon",
    rating: 4.8,
    category: "Livestock",
    image: "https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?auto=format&fit=crop&w=500&q=80",
  },
];

export default products;
